# Generated by Django 5.1.3 on 2025-03-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_user_first_name'),
        ('webapp', '0002_auto_20250327_1705'),
    ]

    operations = [
    ]
