# Generated by Django 2.2.28 on 2025-03-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20250322_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_maps_link',
            field=models.URLField(blank=True),
        ),
    ]
