# Generated by Django 2.2.28 on 2025-03-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_event_google_maps_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='google_maps_link',
            field=models.TextField(blank=True, help_text='Paste the Google Maps link'),
        ),
    ]
