# Generated by Django 2.2.28 on 2025-03-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20250322_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='google_maps_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
