# Generated by Django 2.2.28 on 2025-03-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_event_event_image'),
        ('webapp', '0004_event_created'),
    ]

    operations = [
    ]
